version: '3.4'

services:
  nginx:
    network_mode: bridge
    container_name: nginx
    image: nginx:1.13.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    ports:
      - 80:80
